### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by mrahmadt** [capacitor-community/firebase-crashlytics#1]
Hello

I know you mentioned android support coming soon, just wondering why? is it a technical issue with Capacitor?

**Comment by josh-m-sharpe** [comment]
Any update/response here?

**Comment by josh-m-sharpe** [comment]
I created a new firebase crashlytics plugin here https://github.com/josh-m-sharpe/capacitor-firebase-crashlytics 

This uses the latest capacitor plugin generator and uses the latest Firebase installation steps instead of the deprecated Fabric steps.

There are still some known issues with the Android implementation, so that side of things is still somewhat unverified.

**Comment by priyankpat** [comment]
Closing this issue as there is now a Android support.
