### ISSUE TITLE
How to configure and use correctly?

### ISSUE THREAD

**Issue by IgorSamer** [capacitor-community/firebase-crashlytics#51]
In addition to the settings mentioned in the README do I need to add the plugin to `MainActivity` on Android like the FirebaseAnalytics and another native plugins?

```
import com.getcapacitor.community.firebaseanalytics.FirebaseAnalytics;
import path.to.firebase.crashlytics.file; ???

// Initializes the Bridge
this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
  // Additional plugins you've installed go here
  add(FirebaseAnalytics.class);
  add(FirebaseCrashlytics.class); ???
  ...
}});
```

And once installed, this plugin catch any errors that crash my app automatically with no need to import the plugin in any module or file like `app.module.ts/app.component.ts`?

**Comment by robingenz** [comment]
Hi @IgorSamer,
since Capacitor v3 plugins are loaded automatically (see [here](https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading)). So you don't need to add the plugin to the `MainActivity`.

> And once installed, this plugin catch any errors that crash my app automatically with no need to import the plugin in any module or file like `app.module.ts/app.component.ts`?

Yes, you just need to install the plugin and configure it correctly.

I'll close the issue for now. Let me know if you have any further questions.

**Comment by IgorSamer** [comment]
I didn't notice the plugin is for v3 because I still use Capacitor v2 actually. In this case, the last updated version for v2 is v0.4.1?

**Comment by robingenz** [comment]
Yes 👍
