### ISSUE TITLE
erro install plugin and build app

### ISSUE THREAD

**Issue by diogodumas78** [capacitor-community/firebase-crashlytics#59]
ERROR in node_modules/@capacitor-community/firebase-crashlytics/dist/esm/index.d.ts:1:13 - error TS1005: '=' expected.

1 import type { FirebaseCrashlyticsPlugin } from './definitions';
              ~
node_modules/@capacitor-community/firebase-crashlytics/dist/esm/index.d.ts:1:48 - error TS1005: ';' expected.

1 import type { FirebaseCrashlyticsPlugin } from './definitions';

**Comment by robingenz** [comment]
Hi @diogodumas78,
thank you for your request.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)).

**Comment by shilpidaswani** [comment]
Hey,
when opened the demo project attached in android Studio, getting the following error

Caused by: org.gradle.api.resources.MissingResourceException: Could not read script '\Downloads\capacitor-firebase-plugin-demo-main\capacitor-firebase-plugin-demo-main\android\capacitor-cordova-android-plugins\cordova.variables.gradle' as it does not exist.


Steps to reproduce
cloned the demo project
added node modules using "npm i"
as android is already added, directly opened in Android Studio.

please let me know if I missed any step and how to fix this.

**Comment by robingenz** [comment]
Please follow the instructions in the [README.md](https://github.com/robingenz/capacitor-firebase-plugin-demo#development-setup-) file.
You still need to run `cap sync`.
